const AllGalleryImages = [
  {
    original: "/assets/images/gallery/all/1.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/2.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/3.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/4.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/5.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/6.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/7.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/8.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/9.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/10.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/11.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/12.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/13.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/14.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/15.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/16.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/17.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/18.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/19.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/20.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/21.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/22.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/23.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/24.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/25.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/26.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/27.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/28.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/29.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/30.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/31.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/32.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/33.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/34.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/35.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/36.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/37.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/38.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/39.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/40.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/41.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/42.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/43.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/44.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/45.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/46.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/47.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/48.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/49.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/50.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/51.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/52.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/53.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/54.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/55.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/56.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/57.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/58.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/59.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/60.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/61.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/62.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/63.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
  {
    original: "/assets/images/gallery/all/64.jpg",
    category: 'Testing',
    width: 4,
    height: 3,
  },
];

export { AllGalleryImages };
